on:

  push:

    branches: [ main ]





jobs:

  get_files:

    name: run_on_pr

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@master

        with:

          fetch-depth: 2

          token: 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




      - name: Modified files

        run: |
          git fetch origin refs/heads/main:refs/remotes/origin/main
          git diff --name-only --diff-filter=d main~ main